### ISSUE TITLE
点击事件下标越界

### ISSUE THREAD

**Issue by a362310485** [sfsheng0322/MarqueeView#24]
等第二轮播放的时候，点击就会下标越界
AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.rongxun.QingTianZhu, PID: 23088
                                                                         java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                             at java.util.ArrayList.get(ArrayList.java:308)
                                                                             at com.rongxun.QingTianZhu.Fragment.HomeFragment$3.onItemClick(HomeFragment.java:208)
                                                                             at com.sunfusheng.marqueeview.MarqueeView$2.onClick(MarqueeView.java:126)
                                                                             at android.view.View.performClick(View.java:5264)
                                                                             at android.view.View$PerformClick.run(View.java:21297)
                                                                             at android.os.Handler.handleCallback(Handler.java:743)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:150)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by a362310485** [comment]
我设置错数据了 = =。
