### ISSUE TITLE
下载的apk闪退

### ISSUE THREAD

**Issue by wangchenghao** [sfsheng0322/MarqueeView#3]
06-07 15:00:07.936 2462-2750/? E/NewLauncher: StartActivity : DEBUG : launchApplication useFlipAnim [true]
06-07 15:00:07.946 2462-30103/? E/NewLauncher: IconCellShoter : ### getIconCellShot in !!
06-07 15:00:07.946 2462-30103/? E/NewLauncher: IconCellShoter : ###### isEnter = true
06-07 15:00:07.946 2462-30103/? E/NewLauncher: IconCellShoter : ###### Launcher isResumed = true
06-07 15:00:07.946 2462-30103/? E/NewLauncher: IconCellShoter : ### getIconCellShot wait 1500  !!
                                               
                                               --------- beginning of /dev/log/system
06-07 15:00:07.946 1668-2263/? E/ActivityManager: setAppStartingWindow app stack
06-07 15:00:07.956 2462-2750/? E/NewLauncher: LauncherSmartisanNew : rendertarget mTexId=960
06-07 15:00:07.956 2462-2750/? E/NewLauncher: LauncherSmartisanNew : rendertarget mTexId=961
06-07 15:00:07.956 1668-1709/? E/WindowManager: Adding starting window for com.sunfusheng.sample / Token{423c4f80 ActivityRecord{4247a368 u0 com.sunfusheng.sample/.MainActivity t100}}: null
06-07 15:00:07.966 2462-2750/? E/NewLauncher: IconCellShoter : ### cell name = com.sunfusheng.sample.MainActivity
06-07 15:00:07.966 2462-2750/? E/NewLauncher: IconCellShoter : DEBUG : getIconCellShot gl event run finish [12] ms
06-07 15:00:07.966 2462-30103/? E/NewLauncher: IconCellShoter : ### getIconCellShot out and now, mIconCellShotInfo.valid = true mIconCellShotInfo.cellPos.width = 270 mIconCellShotInfo.cellRec.width = 270 mIconCellShotInfo.shadowRect.width = 270
06-07 15:00:08.006 31116-31116/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sunfusheng.sample, PID: 31116
                                                   java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.sunfusheng.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sunfusheng.sample-1, /vendor/lib, /system/lib]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4386)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:145)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.sunfusheng.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sunfusheng.sample-1, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4386) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:145) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5094) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
06-07 15:00:08.026 2462-2751/? E/NewLauncher: DatabaseHandler : DEBUG : handleEventRemoveNewFlagByIntent ids size 0

**Comment by sfsheng0322** [comment]
你手机的型号是什么啊

**Comment by wangchenghao** [comment]
@sfsheng0322 是锤子哈~

**Comment by sfsheng0322** [comment]
我更新了下，你试试，如果还是不行，麻烦你自己看看啦，没有锤子手机，呜呜

**Comment by wangchenghao** [comment]
@sfsheng0322 亲测已经解决了哈~
