### ISSUE TITLE
java.lang.NullPointerException  getInAnimation().setAnimationListener

### ISSUE THREAD

**Issue by tracyliu1** [sfsheng0322/MarqueeView#37]
`08-24 12:16:51.943 29855-29855/com.echo.launcher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.echo.launcher, PID: 29855
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.animation.Animation.setAnimationListener(android.view.animation.Animation$AnimationListener)' on a null object reference
                                                                       at com.sunfusheng.marqueeview.MarqueeView.start(MarqueeView.java:211)
                                                                       at com.sunfusheng.marqueeview.MarqueeView.startWithFixedWidth(MarqueeView.java:174)
                                                                       at com.sunfusheng.marqueeview.MarqueeView.access$000(MarqueeView.java:23)
                                                                       at com.sunfusheng.marqueeview.MarqueeView$1.onGlobalLayout(MarqueeView.java:141)
                                                                       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1977)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by sfsheng0322** [comment]
V1.3.2改了奔溃的问题，是我的大意，谢谢你哈
