### ISSUE TITLE
调用startWithText（“阿萨德法师法是”）就崩溃

### ISSUE THREAD

**Issue by 11621546** [sfsheng0322/MarqueeView#39]
Process: com.ycl.chinacarpad, PID: 31325
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.animation.Animation.setAnimationListener(android.view.animation.Animation$AnimationListener)' on a null object reference
                                                                         at com.sunfusheng.marqueeview.MarqueeView.start(MarqueeView.java:211)
                                                                         at com.sunfusheng.marqueeview.MarqueeView.startWithFixedWidth(MarqueeView.java:174)
                                                                         at com.sunfusheng.marqueeview.MarqueeView.access$000(MarqueeView.java:23)
                                                                         at com.sunfusheng.marqueeview.MarqueeView$1.onGlobalLayout(MarqueeView.java:141)
                                                                         at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1997)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1161)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6198)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5280)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by sfsheng0322** [comment]
V1.3.2改了奔溃的问题，是我的大意，谢谢你哈
