### ISSUE TITLE
Please set the width of MarqueeView ! 这是什么原因导致的，需要指定一个宽度吗

### ISSUE THREAD

**Issue by assess15** [sfsheng0322/MarqueeView#53]
java.lang.RuntimeException: Please set the width of MarqueeView !
                      at com.sunfusheng.marqueeview.MarqueeView.startWithFixedWidth(MarqueeView.java:155)
                      at com.sunfusheng.marqueeview.MarqueeView.access$000(MarqueeView.java:23)
                      at com.sunfusheng.marqueeview.MarqueeView$1.onGlobalLayout(MarqueeView.java:141)
                      at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2001)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                      at android.view.Choreographer.doFrame(Choreographer.java:608)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                      at android.os.Handler.handleCallback(Handler.java:742)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:157)
                      at android.app.ActivityThread.main(ActivityThread.java:5567)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by sendtion** [comment]
我也遇到了，请问是什么问题？

**Comment by darrenjh** [comment]
什么原因？ 竟然关闭了没解答

**Comment by stonebirds** [comment]
这是为什么关闭问题啊，我也遇到啦

**Comment by klzhong69** [comment]
解决不了就关
